### PR TITLE
Allow multiple browsers

### PR DESCRIPTION
**Pull request by aiji42**
## Overview

Close: #335 

Allows VRT to run in multiple browsers at once.

```ts
import { CustomProjectConfig } from 'lost-pixel';

export const config: CustomProjectConfig = {
  browser: ['chromium', 'firefox', 'webkit'],
  storybookShots: {
    storybookUrl: './storybook-static',
  },
  generateOnly: true,
  failOnDifference: true,
};
```

```
Trying to collect stories via window object
Found 8 stories
Prepared 9 stories for screenshots on chromium
[1/9] Taking screenshot of 'example-button--primary__[w420px|chromium] [420]' (example-button--primary__[w420px|chromium])
[2/9] Taking screenshot of 'example-button--primary__[w1000px|chromium] [1000]' (example-button--primary__[w1000px|chromium])
...
Prepared 9 stories for screenshots on firefox
[1/9] Taking screenshot of 'example-button--primary__[w420px|firefox] [420]' (example-button--primary__[w420px|firefox])
[2/9] Taking screenshot of 'example-button--primary__[w1000px|firefox] [1000]' (example-button--primary__[w1000px|firefox])
...
Prepared 9 stories for screenshots on webkit
[1/9] Taking screenshot of 'example-button--primary__[w420px|webkit] [420]' (example-button--primary__[w420px|webkit])
[2/9] Taking screenshot of 'example-button--primary__[w1000px|webkit] [1000]' (example-button--primary__[w1000px|webkit])
...
Comparing 27 screenshots using 'pixelmatch' as compare engine
[1/27] Comparing 'example-button--primary__[w420px|chromium]' (example-button--primary__[w420px|chromium])
[1/27] Baseline image missing. Will be treated as addition. (example-button--primary__[w420px|chromium])
...
[27/27] Comparing 'example-page--logged-out__[webkit]' (example-page--logged-out__[webkit])
[27/27] Baseline image missing. Will be treated as addition. (example-page--logged-out__[webkit])
Comparison done!
👋 Exiting process with 0 found differences & 27 baselines to update
```

## All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/lost-pixel/lost-pixel/blob/main/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lost-pixel/lost-pixel/pulls) for the same update/change?

### New Feature Submissions:

1. [x] Was the new feature discussed with core maintainers? #335 
2. [x] Does your submission pass tests?
3. [x] Have you lint your code locally before submission?
4. [x] Does the change require an update in documentation? Have you updated the documentation in case it's true?

### CODE REVIEW

**Comment by d-ivashchuk** [comment]
@aiji42 kinda missed your PR! nice work, do you want to share a a little bit more on what has been covered so I could use that as docs addition? thanks a lot for the contribution!

**Comment by aiji42** [comment]
@d-ivashchuk Appreciate your interest in the PR. I've enhanced the lost-pixel to accept an array of browser keys (`'chromium'`, `'firefox'`, `'webkit'`) for VRT. This update maintains backward compatibility, allowing single browser key specification as before. In a single test run, it captures and performs VRT for each specified browser, with file names like `example-page--logged-out__[chromium].png`. For a single browser key, the file naming remains unchanged, ensuring backward compatibility, e.g., `example-page--logged-out.png`.

Do you have any other questions or need further clarification on these changes?

**Comment by d-ivashchuk** [comment]
This is awesome @aiji42! I guess you've made sure that whenever the browser shots are made they are also account the breakpoints provided so we have `shot__[browser]__[breakpoint]` convention. This would allow users to do various size shots on various browsers!

**Comment by aiji42** [comment]
@d-ivashchuk
I forgot to mention, but currently, the captures are already formatted as `shot__[breakpoint|browser]` (e.g., `example-button--primary__[w420px|chromium]`). If the format `shot__[browser]__[breakpoint]` is preferred, I can make that change. However, do you think this alteration is necessary?

**Comment by chriskalmar** [comment]
@aiji42 @d-ivashchuk actually, I prefer the breakpoint and browser to be together within the brackets `[breakpoint|browser]` (as it is right now).
this way it keeps all variations within those brackets.

the failing build was because of a broken package-lock on the main branch. I fixed it today.

will review the PR now. thanks for the contribution @aiji42

**Review by chriskalmar — APPROVED** [review]
nice job @aiji42  👍

**Pull request merged**
