### PR TITLE
Add flakyness retries to the docs

### PR DESCRIPTION
**Pull request by SrBrahma**
All Submissions:

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/lost-pixel/lost-pixel/blob/main/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lost-pixel/lost-pixel/pulls) for the same update/change?

### CODE REVIEW

**Comment by d-ivashchuk** [comment]
@SrBrahma what about adding this to recipes as well? 😀 would be super awesome if we can handle that in this pr!

**Comment by SrBrahma** [comment]
I will do it on Monday ;)

**Comment by SrBrahma** [comment]
@d-ivashchuk Just added it! Let me know if you want further improvements on it.

**Comment by d-ivashchuk** [comment]
Thanks a lot for the great contribution @SrBrahma

**Pull request merged**
