### PR TITLE
Fix config path construction on Windows Issue #208 

### PR DESCRIPTION
**Pull request by trebconnell**
Fix for: #208 

I tried running lint and test on my machine, but they hit other Windows issues.  Gonna have to rely on CI I think 😅

### CODE REVIEW

**Comment by d-ivashchuk** [comment]
hey @trebconnell, thanks a lot for taking the time to come up with PR! Let's see how it will look on the CI in terms of tests! Does it work if you execute it locally on Windows? We developed it on Mac machines for Mac machines initially, having somebody trying it out on windows is really great :D

**Comment by d-ivashchuk** [comment]
Would love to know as well what kind of issues are you facing with lining and testing on the windows machine - we can make it easier for wider public to contribute if we dig into that :D thanks!

**Review by chriskalmar — APPROVED** [review]
Nice 👍

**Review by d-ivashchuk — APPROVED** [review]

**Comment by chriskalmar** [comment]
Released in v2.22.2

**Pull request merged**
